-- OpenCode Manager Theme (auto-generated, do not edit)
vim.cmd('highlight clear')
vim.o.termguicolors = true
vim.g.colors_name = 'opencode'

local hi = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Editor UI
hi('Normal', { fg = '#edecee', bg = '#0f0f0f' })
hi('NormalFloat', { fg = '#edecee', bg = '#15141b' })
hi('FloatBorder', { fg = '#2d2d2d', bg = '#15141b' })
hi('CursorLine', { bg = '#15141b' })
hi('CursorLineNr', { fg = '#a277ff', bold = true })
hi('LineNr', { fg = '#2d2d2d' })
hi('Visual', { bg = '#15141b' })
hi('Search', { fg = '#0f0f0f', bg = '#ffca85' })
hi('IncSearch', { fg = '#0f0f0f', bg = '#a277ff' })
hi('StatusLine', { fg = '#edecee', bg = '#15141b' })
hi('StatusLineNC', { fg = '#6d6d6d', bg = '#15141b' })
hi('TabLine', { fg = '#6d6d6d', bg = '#15141b' })
hi('TabLineSel', { fg = '#edecee', bg = '#0f0f0f', bold = true })
hi('TabLineFill', { bg = '#15141b' })
hi('Pmenu', { fg = '#edecee', bg = '#15141b' })
hi('PmenuSel', { fg = '#edecee', bg = '#15141b' })
hi('PmenuSbar', { bg = '#15141b' })
hi('PmenuThumb', { bg = '#2d2d2d' })
hi('WinSeparator', { fg = '#2d2d2d' })
hi('VertSplit', { fg = '#2d2d2d' })
hi('SignColumn', { bg = '#0f0f0f' })
hi('FoldColumn', { fg = '#2d2d2d', bg = '#0f0f0f' })
hi('Folded', { fg = '#6d6d6d', bg = '#15141b' })
hi('ColorColumn', { bg = '#15141b' })
hi('MsgArea', { fg = '#edecee' })
hi('MoreMsg', { fg = '#61ffca' })
hi('ErrorMsg', { fg = '#ff6767' })
hi('WarningMsg', { fg = '#ffca85' })
hi('Question', { fg = '#f694ff' })
hi('Title', { fg = '#a277ff', bold = true })
hi('Directory', { fg = '#f694ff' })
hi('MatchParen', { fg = '#a277ff', bold = true, underline = true })
hi('NonText', { fg = '#2d2d2d' })
hi('SpecialKey', { fg = '#2d2d2d' })
hi('Conceal', { fg = '#6d6d6d' })
hi('Cursor', { fg = '#0f0f0f', bg = '#a277ff' })
hi('WildMenu', { fg = '#edecee', bg = '#15141b' })

-- Syntax
hi('Comment', { fg = '#6d6d6d', italic = true })
hi('Constant', { fg = '#a277ff' })
hi('String', { fg = '#61ffca' })
hi('Character', { fg = '#61ffca' })
hi('Number', { fg = '#a277ff' })
hi('Boolean', { fg = '#a277ff' })
hi('Float', { fg = '#a277ff' })
hi('Identifier', { fg = '#edecee' })
hi('Function', { fg = '#f694ff' })
hi('Statement', { fg = '#a277ff' })
hi('Conditional', { fg = '#a277ff' })
hi('Repeat', { fg = '#a277ff' })
hi('Label', { fg = '#a277ff' })
hi('Operator', { fg = '#6d6d6d' })
hi('Keyword', { fg = '#a277ff' })
hi('Exception', { fg = '#ff6767' })
hi('PreProc', { fg = '#a277ff' })
hi('Include', { fg = '#f694ff' })
hi('Define', { fg = '#a277ff' })
hi('Macro', { fg = '#a277ff' })
hi('Type', { fg = '#a277ff' })
hi('StorageClass', { fg = '#a277ff' })
hi('Structure', { fg = '#a277ff' })
hi('Typedef', { fg = '#a277ff' })
hi('Special', { fg = '#a277ff' })
hi('SpecialChar', { fg = '#a277ff' })
hi('Tag', { fg = '#f694ff' })
hi('Delimiter', { fg = '#6d6d6d' })
hi('SpecialComment', { fg = '#6d6d6d', bold = true })
hi('Debug', { fg = '#ff6767' })
hi('Underlined', { fg = '#f694ff', underline = true })
hi('Error', { fg = '#ff6767' })
hi('Todo', { fg = '#ffca85', bold = true })

-- Treesitter
hi('@variable', { fg = '#edecee' })
hi('@variable.builtin', { fg = '#ff6767' })
hi('@variable.parameter', { fg = '#edecee', italic = true })
hi('@constant', { fg = '#a277ff' })
hi('@constant.builtin', { fg = '#a277ff' })
hi('@constant.macro', { fg = '#a277ff' })
hi('@module', { fg = '#a277ff' })
hi('@string', { fg = '#61ffca' })
hi('@string.escape', { fg = '#a277ff' })
hi('@string.regex', { fg = '#a277ff' })
hi('@character', { fg = '#61ffca' })
hi('@number', { fg = '#a277ff' })
hi('@boolean', { fg = '#a277ff' })
hi('@float', { fg = '#a277ff' })
hi('@function', { fg = '#f694ff' })
hi('@function.builtin', { fg = '#f694ff', italic = true })
hi('@function.macro', { fg = '#a277ff' })
hi('@method', { fg = '#f694ff' })
hi('@constructor', { fg = '#f694ff' })
hi('@property', { fg = '#edecee' })
hi('@field', { fg = '#edecee' })
hi('@parameter', { fg = '#edecee', italic = true })
hi('@keyword', { fg = '#a277ff' })
hi('@keyword.function', { fg = '#a277ff' })
hi('@keyword.return', { fg = '#a277ff' })
hi('@keyword.operator', { fg = '#a277ff' })
hi('@operator', { fg = '#6d6d6d' })
hi('@punctuation.bracket', { fg = '#6d6d6d' })
hi('@punctuation.delimiter', { fg = '#6d6d6d' })
hi('@punctuation.special', { fg = '#a277ff' })
hi('@type', { fg = '#a277ff' })
hi('@type.builtin', { fg = '#a277ff', italic = true })
hi('@type.qualifier', { fg = '#a277ff' })
hi('@tag', { fg = '#f694ff' })
hi('@tag.attribute', { fg = '#a277ff' })
hi('@tag.delimiter', { fg = '#6d6d6d' })
hi('@text.literal', { fg = '#61ffca' })
hi('@text.reference', { fg = '#f694ff' })
hi('@text.title', { fg = '#a277ff', bold = true })
hi('@text.uri', { fg = '#f694ff', underline = true })
hi('@text.emphasis', { italic = true })
hi('@text.strong', { bold = true })
hi('@comment', { fg = '#6d6d6d', italic = true })

-- Diagnostics
hi('DiagnosticError', { fg = '#ff6767' })
hi('DiagnosticWarn', { fg = '#ffca85' })
hi('DiagnosticInfo', { fg = '#a277ff' })
hi('DiagnosticHint', { fg = '#61ffca' })
hi('DiagnosticUnderlineError', { sp = '#ff6767', undercurl = true })
hi('DiagnosticUnderlineWarn', { sp = '#ffca85', undercurl = true })
hi('DiagnosticUnderlineInfo', { sp = '#a277ff', undercurl = true })
hi('DiagnosticUnderlineHint', { sp = '#61ffca', undercurl = true })
hi('DiagnosticVirtualTextError', { fg = '#ff6767', bg = '#15141b' })
hi('DiagnosticVirtualTextWarn', { fg = '#ffca85', bg = '#15141b' })
hi('DiagnosticVirtualTextInfo', { fg = '#a277ff', bg = '#15141b' })
hi('DiagnosticVirtualTextHint', { fg = '#61ffca', bg = '#15141b' })
hi('DiagnosticSignError', { fg = '#ff6767' })
hi('DiagnosticSignWarn', { fg = '#ffca85' })
hi('DiagnosticSignInfo', { fg = '#a277ff' })
hi('DiagnosticSignHint', { fg = '#61ffca' })

-- Git signs
hi('GitSignsAdd', { fg = '#61ffca' })
hi('GitSignsChange', { fg = '#ffca85' })
hi('GitSignsDelete', { fg = '#ff6767' })
hi('DiffAdd', { fg = '#61ffca', bg = '#15141b' })
hi('DiffChange', { fg = '#ffca85', bg = '#15141b' })
hi('DiffDelete', { fg = '#ff6767', bg = '#15141b' })
hi('DiffText', { fg = '#f694ff', bg = '#15141b' })

-- Telescope
hi('TelescopeNormal', { fg = '#edecee', bg = '#15141b' })
hi('TelescopeBorder', { fg = '#2d2d2d', bg = '#15141b' })
hi('TelescopeSelection', { fg = '#edecee', bg = '#15141b' })
hi('TelescopeSelectionCaret', { fg = '#a277ff', bg = '#15141b' })
hi('TelescopeMatching', { fg = '#a277ff' })
hi('TelescopePromptPrefix', { fg = '#a277ff' })
hi('TelescopePromptTitle', { fg = '#0f0f0f', bg = '#a277ff', bold = true })
hi('TelescopePreviewTitle', { fg = '#0f0f0f', bg = '#61ffca', bold = true })
hi('TelescopeResultsTitle', { fg = '#0f0f0f', bg = '#f694ff', bold = true })

-- LSP
hi('LspReferenceText', { bg = '#15141b' })
hi('LspReferenceRead', { bg = '#15141b' })
hi('LspReferenceWrite', { bg = '#15141b' })
