import { PaletteItem, CommandPaletteProps } from "./types";

/**
 * Build the full palette item list from component props.
 * Extracted to keep the main component file under 300 lines.
 */
export function buildPaletteItems(props: CommandPaletteProps): PaletteItem[] {
  const {
    onClose,
    onCommand,
    onNewSession,
    onToggleSidebar,
    onToggleTerminal,
    onOpenModelPicker,
    onOpenCheatsheet,
    onOpenTodoPanel,
    onOpenSessionSelector,
    onOpenContextInput,
    onOpenSettings,
    onOpenWatcher,
    onOpenContextWindow,
    onOpenDiffReview,
    onOpenSearch,
    onOpenCrossSearch,
    onOpenSplitView,
    onOpenSessionGraph,
    onOpenSessionDashboard,
    onOpenActivityFeed,
    onOpenNotificationPrefs,
    onOpenInbox,
    onOpenAssistantCenter,
    onOpenMemory,
    onOpenAutonomy,
    onOpenRoutines,
    onOpenDelegation,
    onOpenWorkspaceManager,
    onOpenMissions,
    onOpenSystemMonitor,
    onOpenSkillsUpload,
    sessionId,
  } = props;

  const items: PaletteItem[] = [
    {
      id: "new-session",
      category: "Sessions",
      label: "New Session",
      shortcut: "Cmd+Shift+N",
      handler: () => { onClose(); onNewSession(); },
    },
    {
      id: "model-picker",
      category: "Core",
      label: "Choose Model",
      shortcut: "Cmd+'",
      handler: () => { onOpenModelPicker(); },
    },
    {
      id: "toggle-sidebar",
      category: "Layout",
      label: "Toggle Sidebar",
      shortcut: "Cmd+B",
      handler: () => { onClose(); onToggleSidebar(); },
    },
    {
      id: "toggle-terminal",
      category: "Layout",
      label: "Toggle Terminal",
      shortcut: "Cmd+`",
      handler: () => { onClose(); onToggleTerminal(); },
    },
    {
      id: "cheatsheet",
      category: "Core",
      label: "Keyboard Shortcuts",
      shortcut: "?",
      handler: () => { onClose(); onOpenCheatsheet(); },
    },
    {
      id: "session-selector",
      category: "Sessions",
      label: "Select Session",
      description: "Search across all projects",
      shortcut: "Cmd+Shift+S",
      handler: () => { onClose(); onOpenSessionSelector(); },
    },
    {
      id: "settings",
      category: "Core",
      label: "Settings",
      description: "Configure panels and theme",
      shortcut: "Cmd+,",
      handler: () => { onClose(); onOpenSettings(); },
    },
    {
      id: "skills-upload",
      category: "Core",
      label: "Upload Skills",
      description: "Upload ZIP file with skills",
      handler: () => { onClose(); onOpenSkillsUpload?.(); },
    },
    {
      id: "watcher",
      category: "Sessions",
      label: "Session Watcher",
      description: "Monitor and auto-continue sessions",
      shortcut: "Cmd+Shift+W",
      handler: () => { onClose(); onOpenWatcher(); },
    },
    {
      id: "context-window",
      category: "Analysis",
      label: "Context Window",
      description: "View token usage breakdown",
      shortcut: "Cmd+Shift+C",
      handler: () => { onClose(); onOpenContextWindow(); },
    },
    {
      id: "diff-review",
      category: "Analysis",
      label: "Diff Review",
      description: "Review file changes made by AI",
      shortcut: "Cmd+Shift+D",
      handler: () => { onClose(); onOpenDiffReview(); },
    },
    {
      id: "search",
      category: "Search",
      label: "Search in Conversation",
      description: "Find text in the current session",
      shortcut: "Cmd+F",
      handler: () => { onClose(); onOpenSearch(); },
    },
    {
      id: "cross-search",
      category: "Search",
      label: "Search All Sessions",
      description: "Search across all sessions in project",
      shortcut: "Cmd+Shift+F",
      handler: () => { onClose(); onOpenCrossSearch(); },
    },
    {
      id: "split-view",
      category: "Layout",
      label: "Split View",
      description: "View two sessions side by side",
      shortcut: "\u2318\\",
      handler: () => { onClose(); onOpenSplitView?.(); },
    },
    {
      id: "session-graph",
      category: "Sessions",
      label: "Session Graph",
      description: "View session dependency tree",
      shortcut: "\u2318\u21E7H",
      handler: () => { onClose(); onOpenSessionGraph?.(); },
    },
    {
      id: "session-dashboard",
      category: "Sessions",
      label: "Session Dashboard",
      description: "Overview of all running sessions",
      shortcut: "\u2318\u21E7O",
      handler: () => { onClose(); onOpenSessionDashboard?.(); },
    },
    {
      id: "activity-feed",
      category: "Sessions",
      label: "Activity Feed",
      description: "View real-time session activity",
      shortcut: "\u2318\u21E7A",
      handler: () => { onClose(); onOpenActivityFeed?.(); },
    },
    {
      id: "notification-prefs",
      category: "Assistant",
      label: "Notification Preferences",
      description: "Configure session alerts",
      shortcut: "\u2318\u21E7I",
      handler: () => { onClose(); onOpenNotificationPrefs?.(); },
    },
    {
      id: "assistant-center",
      category: "Assistant",
      label: "Assistant Center",
      description: "Open the assistant cockpit",
      shortcut: "\u2318\u21E7.",
      handler: () => { onClose(); onOpenAssistantCenter?.(); },
    },
    {
      id: "assistant-inbox",
      category: "Assistant",
      label: "Assistant Inbox",
      description: "Review everything that needs attention",
      shortcut: "\u2318\u21E7U",
      handler: () => { onClose(); onOpenInbox?.(); },
    },
    {
      id: "missions",
      category: "Assistant",
      label: "Missions",
      description: "Track high-level goals above sessions",
      shortcut: "\u2318\u21E7M",
      handler: () => { onClose(); onOpenMissions?.(); },
    },
    {
      id: "delegation-board",
      category: "Assistant",
      label: "Delegation Board",
      description: "Track delegated work and linked outputs",
      shortcut: "\u2318\u21E7B",
      handler: () => { onClose(); onOpenDelegation?.(); },
    },
    {
      id: "routines",
      category: "Assistant",
      label: "Routines",
      description: "Manage recurring assistant workflows",
      shortcut: "\u2318\u21E7R",
      handler: () => { onClose(); onOpenRoutines?.(); },
    },
    {
      id: "autonomy",
      category: "Assistant",
      label: "Autonomy",
      description: "Choose proactive assistant mode",
      shortcut: "\u2318\u21E7J",
      handler: () => { onClose(); onOpenAutonomy?.(); },
    },
    {
      id: "personal-memory",
      category: "Assistant",
      label: "Personal Memory",
      description: "Store preferences and working norms",
      shortcut: "\u2318\u21E7Y",
      handler: () => { onClose(); onOpenMemory?.(); },
    },
    {
      id: "workspace-manager",
      category: "Assistant",
      label: "Workspaces",
      description: "Save and restore workspace layouts",
      shortcut: "\u2318\u21E7L",
      handler: () => { onClose(); onOpenWorkspaceManager?.(); },
    },
    {
      id: "system-monitor",
      category: "System",
      label: "System Monitor",
      description: "htop-like system resource monitor",
      handler: () => { onClose(); onOpenSystemMonitor?.(); },
    },
    {
      id: "refresh",
      category: "System",
      label: "Refresh Page",
      description: "Reload the application",
      handler: () => { onClose(); window.location.reload(); },
    },
  ];

  // Session-specific items
  if (sessionId) {
    items.push(
      {
        id: "todo-panel",
        category: "Sessions",
        label: "Todo Panel",
        description: "View session todos",
        shortcut: "Cmd+Shift+T",
        handler: () => { onClose(); onOpenTodoPanel(); },
      },
      {
        id: "context-input",
        category: "Sessions",
        label: "Send Context",
        description: "Send context to the AI session",
        shortcut: "Cmd+Shift+K",
        handler: () => { onClose(); onOpenContextInput(); },
      },
      {
        id: "compact",
        category: "Sessions",
        label: "Compact History",
        description: "Compact conversation to reduce tokens",
        handler: () => { onClose(); onCommand("compact"); },
      },
      {
        id: "undo",
        category: "Sessions",
        label: "Undo",
        description: "Undo last action",
        handler: () => { onClose(); onCommand("undo"); },
      },
      {
        id: "redo",
        category: "Sessions",
        label: "Redo",
        description: "Redo last action",
        handler: () => { onClose(); onCommand("redo"); },
      },
      {
        id: "fork",
        category: "Sessions",
        label: "Fork Session",
        description: "Create a copy of this session",
        handler: () => { onClose(); onCommand("fork"); },
      },
      {
        id: "share",
        category: "Sessions",
        label: "Share Session",
        description: "Get a shareable link",
        handler: () => { onClose(); onCommand("share"); },
      },
    );
  }

  return items;
}
