import type { CommandDef } from "../types";

/** The conversation surface: composer, transcript navigation and the docks. */
export const CHAT_COMMANDS: readonly CommandDef[] = [
  { id: "chat.focusComposer", title: "Focus Composer", category: "Chat" },
  { id: "chat.send", title: "Send Message", category: "Chat", when: "composerFocused" },
  { id: "chat.newline", title: "Insert Newline", category: "Chat", when: "composerFocused" },
  { id: "chat.abort", title: "Stop Generating", category: "Chat", when: "sessionBusy", label: "abort" },
  { id: "chat.slashCommands", title: "Slash Commands", category: "Chat", when: "sessionActive", label: "slash" },
  { id: "chat.mention", title: "Mention File or Agent", category: "Chat", when: "composerFocused" },
  { id: "chat.attachImage", title: "Attach Image", category: "Chat", when: "sessionActive", label: "picture" },
  { id: "chat.attachTerminal", title: "Attach Terminal to Session", category: "Chat", when: "sessionActive", label: "terminal" },
  { id: "chat.queuePanel", title: "Show Queued Messages", category: "Chat", when: "hasQueue", label: "queue" },
  { id: "chat.clearQueue", title: "Clear Queued Messages", category: "Chat", when: "hasQueue", label: "clear queue" },
  { id: "chat.undoTurn", title: "Undo Last Turn", category: "Chat", when: "sessionActive" },
  { id: "chat.redoTurn", title: "Redo Last Turn", category: "Chat", when: "sessionActive" },
  { id: "chat.retry", title: "Retry Last Message", category: "Chat", when: "sessionActive", label: "retry" },
  { id: "chat.compact", title: "Compact History", category: "Chat", when: "sessionActive", label: "compact" },
  { id: "chat.clear", title: "Clear Conversation", category: "Chat", when: "sessionActive", label: "clear" },
  { id: "chat.sendContext", title: "Send Context to Session", category: "Chat", when: "sessionActive", label: "send context" },
  { id: "chat.contextWindow", title: "Context Window", category: "Chat", when: "sessionActive", label: "context window" },
  { id: "chat.todoPanel", title: "Todo Panel", category: "Chat", when: "sessionActive", label: "todos" },
  { id: "chat.usage", title: "Session Usage and Cost", category: "Chat", when: "sessionActive", label: "usage" },
  { id: "chat.find", title: "Find in Conversation", category: "Chat", label: "search" },
  { id: "chat.findNext", title: "Next Match", category: "Chat", when: "findOpen" },
  { id: "chat.findPrevious", title: "Previous Match", category: "Chat", when: "findOpen" },
  { id: "chat.nextMessage", title: "Next Message", category: "Chat" },
  { id: "chat.previousMessage", title: "Previous Message", category: "Chat" },
  { id: "chat.scrollDown", title: "Scroll Down", category: "Chat" },
  { id: "chat.scrollUp", title: "Scroll Up", category: "Chat" },
  { id: "chat.scrollTop", title: "Go to First Message", category: "Chat" },
  { id: "chat.scrollBottom", title: "Go to Latest Message", category: "Chat" },
  { id: "chat.toggleToolCall", title: "Expand or Collapse Tool Call", category: "Chat" },
  { id: "chat.expandAll", title: "Expand All Tool Calls", category: "Chat" },
  { id: "chat.collapseAll", title: "Collapse All Tool Calls", category: "Chat" },
  { id: "chat.copyResponse", title: "Copy Last Response", category: "Chat", when: "sessionActive", label: "response" },
  { id: "chat.copyTranscript", title: "Copy Transcript", category: "Chat", when: "sessionActive", label: "transcript" },
  { id: "chat.copyCodeBlock", title: "Copy Focused Code Block", category: "Chat", label: "code block" },
  { id: "permission.allowOnce", title: "Permission: Allow Once", category: "Chat", when: "permissionPending" },
  { id: "permission.allowAlways", title: "Permission: Always Allow", category: "Chat", when: "permissionPending" },
  { id: "permission.reject", title: "Permission: Reject", category: "Chat", when: "permissionPending" },
  { id: "question.submit", title: "Submit Answers", category: "Chat", when: "questionPending" },
  { id: "question.dismiss", title: "Dismiss Question", category: "Chat", when: "questionPending" },
];
