/** Browser KeyboardEvent.key names and their Neovim key notation names. */
export const KEY_TABLE: Readonly<Record<string, string>> = Object.freeze({
  Enter: "CR",
  Escape: "Esc",
  Backspace: "BS",
  Tab: "Tab",
  Delete: "Del",
  Insert: "Insert",
  Home: "Home",
  End: "End",
  PageUp: "PageUp",
  PageDown: "PageDown",
  ArrowUp: "Up",
  ArrowDown: "Down",
  ArrowLeft: "Left",
  ArrowRight: "Right",
  Undo: "Undo",
  Help: "Help",
  F1: "F1",
  F2: "F2",
  F3: "F3",
  F4: "F4",
  F5: "F5",
  F6: "F6",
  F7: "F7",
  F8: "F8",
  F9: "F9",
  F10: "F10",
  F11: "F11",
  F12: "F12",
  F13: "F13",
  F14: "F14",
  F15: "F15",
  F16: "F16",
  F17: "F17",
  F18: "F18",
  F19: "F19",
  F20: "F20",
  F21: "F21",
  F22: "F22",
  F23: "F23",
  F24: "F24",
  F25: "F25",
  F26: "F26",
  F27: "F27",
  F28: "F28",
  F29: "F29",
  F30: "F30",
  F31: "F31",
  F32: "F32",
  F33: "F33",
  F34: "F34",
  F35: "F35",
  F36: "F36",
  F37: "F37",
});

export const KEYPAD_TABLE: Readonly<Record<string, string>> = Object.freeze({
  NumpadEnter: "kEnter",
  NumpadAdd: "kPlus",
  NumpadSubtract: "kMinus",
  NumpadMultiply: "kMultiply",
  NumpadDivide: "kDivide",
  NumpadDecimal: "kPoint",
  Numpad0: "k0",
  Numpad1: "k1",
  Numpad2: "k2",
  Numpad3: "k3",
  Numpad4: "k4",
  Numpad5: "k5",
  Numpad6: "k6",
  Numpad7: "k7",
  Numpad8: "k8",
  Numpad9: "k9",
});

export const MODIFIER_KEYS: ReadonlySet<string> = new Set([
  "Shift", "Control", "Alt", "Meta", "AltGraph", "CapsLock", "Dead",
]);

export const KEY_TABLE_NOTATIONS: readonly string[] = Object.freeze([
  ...new Set([...Object.values(KEY_TABLE), ...Object.values(KEYPAD_TABLE)]),
]);
