/**
 * lspMarkdown — render the markdown language servers actually send.
 *
 * Hover and completion documentation arrive as `MarkupContent` with
 * `kind: "markdown"`, and for a typed language that is most of the value:
 * rust-analyzer answers a hover with a fenced `rust` block holding the
 * signature, then prose, then a link to the docs. Printed as plain text that is
 * a wall of backticks and pipe characters.
 *
 * These tooltips live in CodeMirror's DOM rather than React's, so this returns
 * an element rather than a component. Everything is sanitised — the content is
 * generated by a program reading the user's own source, but it reaches us as
 * HTML-capable markdown and is not worth trusting.
 */
import { marked } from "marked";
import DOMPurify from "dompurify";

marked.setOptions({ gfm: true, breaks: false });

/** Tags a hover card has any business containing. */
const ALLOWED_TAGS = [
  "p", "br", "hr", "em", "strong", "del", "code", "pre", "span",
  "a", "ul", "ol", "li", "blockquote",
  "h1", "h2", "h3", "h4", "h5", "h6",
  "table", "thead", "tbody", "tr", "th", "td",
];

export function renderMarkdown(source: string): string {
  const html = marked.parse(source, { async: false }) as string;
  return DOMPurify.sanitize(html, {
    ALLOWED_TAGS,
    ALLOWED_ATTR: ["href", "title", "class"],
    // Anything with a target is opened by us below, not by the markup.
    FORBID_ATTR: ["target", "style", "onclick"],
  });
}

/**
 * Build the DOM node for a markdown tooltip.
 *
 * `className` lets hover and completion documentation share the renderer while
 * keeping separate sizing.
 */
export function markdownElement(source: string, className: string): HTMLElement {
  const dom = document.createElement("div");
  dom.className = className;
  dom.innerHTML = renderMarkdown(source);

  // Links inside an editor tooltip must not navigate the app away from the
  // file the reader is in the middle of.
  dom.querySelectorAll("a").forEach((anchor) => {
    anchor.setAttribute("target", "_blank");
    anchor.setAttribute("rel", "noreferrer noopener");
  });
  return dom;
}
