import type { WorkspaceSnapshot } from "../api";

/** Pre-built task templates. */
export const TASK_TEMPLATES: WorkspaceSnapshot[] = [
  {
    name: "Debug Mode",
    created_at: "",
    panels: { sidebar: false, terminal: true, editor: true, git: false },
    layout: { sidebar_width: 0, terminal_height: 300, side_panel_width: 0 },
    open_files: [],
    active_file: null,
    terminal_tabs: [{ label: "Test Runner", kind: "shell" }],
    session_id: null,
    git_branch: null,
    is_template: true,
    recipe_description: "Open the editor and terminal for active debugging.",
    recipe_next_action: "Run tests and inspect the active failure.",
    is_recipe: true,
  },
  {
    name: "Review Mode",
    created_at: "",
    panels: { sidebar: false, terminal: false, editor: true, git: true },
    layout: { sidebar_width: 0, terminal_height: 0, side_panel_width: 480 },
    open_files: [],
    active_file: null,
    terminal_tabs: [],
    session_id: null,
    git_branch: null,
    is_template: true,
    recipe_description: "Open review-focused panels for git inspection.",
    recipe_next_action: "Review diffs and summarize the branch state.",
    is_recipe: true,
  },
  {
    name: "Terminal Focus",
    created_at: "",
    panels: { sidebar: false, terminal: true, editor: false, git: false },
    layout: { sidebar_width: 0, terminal_height: 600, side_panel_width: 0 },
    open_files: [],
    active_file: null,
    terminal_tabs: [{ label: "Shell", kind: "shell" }],
    session_id: null,
    git_branch: null,
    is_template: true,
    recipe_description: "Maximize terminal space for shell-driven work.",
    recipe_next_action: "Run the next command-line workflow.",
    is_recipe: true,
  },
];
